set_property PACKAGE_PIN P18 [get_ports {red_0}]					
set_property IOSTANDARD LVCMOS33 [get_ports {red_0}]
set_property PACKAGE_PIN A14 [get_ports {green_0}]					
set_property IOSTANDARD LVCMOS33 [get_ports {green_0}]
set_property PACKAGE_PIN R18 [get_ports {blue_0}]					
set_property IOSTANDARD LVCMOS33 [get_ports {blue_0}]

set_property PACKAGE_PIN J1 [get_ports {red_1}]					
set_property IOSTANDARD LVCMOS33 [get_ports {red_1}]
set_property PACKAGE_PIN L2 [get_ports {green_1}]					
set_property IOSTANDARD LVCMOS33 [get_ports {green_1}]
set_property PACKAGE_PIN H1 [get_ports {blue_1}]					
set_property IOSTANDARD LVCMOS33 [get_ports {blue_1}]

set_property PACKAGE_PIN K2 [get_ports {red_2}]					
set_property IOSTANDARD LVCMOS33 [get_ports {red_2}]
set_property PACKAGE_PIN G3 [get_ports {green_2}]					
set_property IOSTANDARD LVCMOS33 [get_ports {green_2}]
set_property PACKAGE_PIN M19 [get_ports {blue_2}]					
set_property IOSTANDARD LVCMOS33 [get_ports {blue_2}]
